// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.32.0
// 	protoc        v5.29.1
// source: api/v1beta/ingestor_api.proto

package metrics

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// WriteMetricsRequest is the request message for WriteMetrics
// The request is a stream of WriteMetricsRequest messages, where each message contains a batch of metrics data
type WriteMetricsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// collection is the name of the collection where the metrics data should be written
	// usually this corresponds to the table name in the database
	Collection string `protobuf:"bytes,1,opt,name=collection,proto3" json:"collection,omitempty"`
	// metrics is the Avro encoded data
	Metrics []byte `protobuf:"bytes,2,opt,name=metrics,proto3" json:"metrics,omitempty"`
	// schema is the byte representation of the Avro schema
	Schema []byte `protobuf:"bytes,3,opt,name=schema,proto3" json:"schema,omitempty"`
	// metadata contains additional metadata about the metrics data
	// e.g. number of rows, whether to include server side timestamp
	Metadata *MetricsMetadata `protobuf:"bytes,4,opt,name=metadata,proto3" json:"metadata,omitempty"`
}

func (x *WriteMetricsRequest) Reset() {
	*x = WriteMetricsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1beta_ingestor_api_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WriteMetricsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteMetricsRequest) ProtoMessage() {}

func (x *WriteMetricsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1beta_ingestor_api_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteMetricsRequest.ProtoReflect.Descriptor instead.
func (*WriteMetricsRequest) Descriptor() ([]byte, []int) {
	return file_api_v1beta_ingestor_api_proto_rawDescGZIP(), []int{0}
}

func (x *WriteMetricsRequest) GetCollection() string {
	if x != nil {
		return x.Collection
	}
	return ""
}

func (x *WriteMetricsRequest) GetMetrics() []byte {
	if x != nil {
		return x.Metrics
	}
	return nil
}

func (x *WriteMetricsRequest) GetSchema() []byte {
	if x != nil {
		return x.Schema
	}
	return nil
}

func (x *WriteMetricsRequest) GetMetadata() *MetricsMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// MetricsMetadata contains additional metadata about the metrics data
// e.g. number of rows, whether to include server side timestamp
type MetricsMetadata struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// number of rows in the metrics data
	Rows uint64 `protobuf:"varint,1,opt,name=rows,proto3" json:"rows,omitempty"`
	// whether to include server side timestamp when writing metrics
	// ignored for METRICS and AGENT_TELEMETRY schema types, timestamp is always included for those
	// by default timestamp will always be included, unless explicitly specified not to
	SkipTimestamp bool `protobuf:"varint,2,opt,name=skip_timestamp,json=skipTimestamp,proto3" json:"skip_timestamp,omitempty"`
	// if skip_timestamp = false and no column name is provided, `timestamp` is assumed as column name
	TimestampColumn *string `protobuf:"bytes,3,opt,name=timestamp_column,json=timestampColumn,proto3,oneof" json:"timestamp_column,omitempty"`
}

func (x *MetricsMetadata) Reset() {
	*x = MetricsMetadata{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1beta_ingestor_api_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MetricsMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetricsMetadata) ProtoMessage() {}

func (x *MetricsMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1beta_ingestor_api_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetricsMetadata.ProtoReflect.Descriptor instead.
func (*MetricsMetadata) Descriptor() ([]byte, []int) {
	return file_api_v1beta_ingestor_api_proto_rawDescGZIP(), []int{1}
}

func (x *MetricsMetadata) GetRows() uint64 {
	if x != nil {
		return x.Rows
	}
	return 0
}

func (x *MetricsMetadata) GetSkipTimestamp() bool {
	if x != nil {
		return x.SkipTimestamp
	}
	return false
}

func (x *MetricsMetadata) GetTimestampColumn() string {
	if x != nil && x.TimestampColumn != nil {
		return *x.TimestampColumn
	}
	return ""
}

// WriteMetricsResponse is the response message for WriteMetrics
type WriteMetricsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// success indicates whether the write operation was successful
	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	// error contains the error message if the write operation failed
	Error *string `protobuf:"bytes,2,opt,name=error,proto3,oneof" json:"error,omitempty"`
}

func (x *WriteMetricsResponse) Reset() {
	*x = WriteMetricsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1beta_ingestor_api_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WriteMetricsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteMetricsResponse) ProtoMessage() {}

func (x *WriteMetricsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1beta_ingestor_api_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteMetricsResponse.ProtoReflect.Descriptor instead.
func (*WriteMetricsResponse) Descriptor() ([]byte, []int) {
	return file_api_v1beta_ingestor_api_proto_rawDescGZIP(), []int{2}
}

func (x *WriteMetricsResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *WriteMetricsResponse) GetError() string {
	if x != nil && x.Error != nil {
		return *x.Error
	}
	return ""
}

var File_api_v1beta_ingestor_api_proto protoreflect.FileDescriptor

var file_api_v1beta_ingestor_api_proto_rawDesc = []byte{
	0x0a, 0x1d, 0x61, 0x70, 0x69, 0x2f, 0x76, 0x31, 0x62, 0x65, 0x74, 0x61, 0x2f, 0x69, 0x6e, 0x67,
	0x65, 0x73, 0x74, 0x6f, 0x72, 0x5f, 0x61, 0x70, 0x69, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x0e, 0x6d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x73, 0x2e, 0x76, 0x31, 0x62, 0x65, 0x74, 0x61, 0x22,
	0xa4, 0x01, 0x0a, 0x13, 0x57, 0x72, 0x69, 0x74, 0x65, 0x4d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x73,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1e, 0x0a, 0x0a, 0x63, 0x6f, 0x6c, 0x6c, 0x65,
	0x63, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x63, 0x6f, 0x6c,
	0x6c, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x74, 0x72, 0x69,
	0x63, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x07, 0x6d, 0x65, 0x74, 0x72, 0x69, 0x63,
	0x73, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x63, 0x68, 0x65, 0x6d, 0x61, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x0c, 0x52, 0x06, 0x73, 0x63, 0x68, 0x65, 0x6d, 0x61, 0x12, 0x3b, 0x0a, 0x08, 0x6d, 0x65, 0x74,
	0x61, 0x64, 0x61, 0x74, 0x61, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1f, 0x2e, 0x6d, 0x65,
	0x74, 0x72, 0x69, 0x63, 0x73, 0x2e, 0x76, 0x31, 0x62, 0x65, 0x74, 0x61, 0x2e, 0x4d, 0x65, 0x74,
	0x72, 0x69, 0x63, 0x73, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x52, 0x08, 0x6d, 0x65,
	0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x22, 0x91, 0x01, 0x0a, 0x0f, 0x4d, 0x65, 0x74, 0x72, 0x69,
	0x63, 0x73, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x12, 0x12, 0x0a, 0x04, 0x72, 0x6f,
	0x77, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x04, 0x72, 0x6f, 0x77, 0x73, 0x12, 0x25,
	0x0a, 0x0e, 0x73, 0x6b, 0x69, 0x70, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0d, 0x73, 0x6b, 0x69, 0x70, 0x54, 0x69, 0x6d, 0x65,
	0x73, 0x74, 0x61, 0x6d, 0x70, 0x12, 0x2e, 0x0a, 0x10, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61,
	0x6d, 0x70, 0x5f, 0x63, 0x6f, 0x6c, 0x75, 0x6d, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x48,
	0x00, 0x52, 0x0f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x43, 0x6f, 0x6c, 0x75,
	0x6d, 0x6e, 0x88, 0x01, 0x01, 0x42, 0x13, 0x0a, 0x11, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74,
	0x61, 0x6d, 0x70, 0x5f, 0x63, 0x6f, 0x6c, 0x75, 0x6d, 0x6e, 0x22, 0x55, 0x0a, 0x14, 0x57, 0x72,
	0x69, 0x74, 0x65, 0x4d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x08, 0x52, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x12, 0x19, 0x0a, 0x05,
	0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x05, 0x65,
	0x72, 0x72, 0x6f, 0x72, 0x88, 0x01, 0x01, 0x42, 0x08, 0x0a, 0x06, 0x5f, 0x65, 0x72, 0x72, 0x6f,
	0x72, 0x32, 0x6d, 0x0a, 0x0c, 0x49, 0x6e, 0x67, 0x65, 0x73, 0x74, 0x69, 0x6f, 0x6e, 0x41, 0x50,
	0x49, 0x12, 0x5d, 0x0a, 0x0c, 0x57, 0x72, 0x69, 0x74, 0x65, 0x4d, 0x65, 0x74, 0x72, 0x69, 0x63,
	0x73, 0x12, 0x23, 0x2e, 0x6d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x73, 0x2e, 0x76, 0x31, 0x62, 0x65,
	0x74, 0x61, 0x2e, 0x57, 0x72, 0x69, 0x74, 0x65, 0x4d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x73, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x24, 0x2e, 0x6d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x73,
	0x2e, 0x76, 0x31, 0x62, 0x65, 0x74, 0x61, 0x2e, 0x57, 0x72, 0x69, 0x74, 0x65, 0x4d, 0x65, 0x74,
	0x72, 0x69, 0x63, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x28, 0x01,
	0x42, 0x2a, 0x5a, 0x28, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x63,
	0x61, 0x73, 0x74, 0x61, 0x69, 0x2f, 0x6d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x73, 0x2f, 0x76, 0x31,
	0x62, 0x65, 0x74, 0x61, 0x3b, 0x6d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x73, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_v1beta_ingestor_api_proto_rawDescOnce sync.Once
	file_api_v1beta_ingestor_api_proto_rawDescData = file_api_v1beta_ingestor_api_proto_rawDesc
)

func file_api_v1beta_ingestor_api_proto_rawDescGZIP() []byte {
	file_api_v1beta_ingestor_api_proto_rawDescOnce.Do(func() {
		file_api_v1beta_ingestor_api_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_v1beta_ingestor_api_proto_rawDescData)
	})
	return file_api_v1beta_ingestor_api_proto_rawDescData
}

var file_api_v1beta_ingestor_api_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_api_v1beta_ingestor_api_proto_goTypes = []interface{}{
	(*WriteMetricsRequest)(nil),  // 0: metrics.v1beta.WriteMetricsRequest
	(*MetricsMetadata)(nil),      // 1: metrics.v1beta.MetricsMetadata
	(*WriteMetricsResponse)(nil), // 2: metrics.v1beta.WriteMetricsResponse
}
var file_api_v1beta_ingestor_api_proto_depIdxs = []int32{
	1, // 0: metrics.v1beta.WriteMetricsRequest.metadata:type_name -> metrics.v1beta.MetricsMetadata
	0, // 1: metrics.v1beta.IngestionAPI.WriteMetrics:input_type -> metrics.v1beta.WriteMetricsRequest
	2, // 2: metrics.v1beta.IngestionAPI.WriteMetrics:output_type -> metrics.v1beta.WriteMetricsResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_api_v1beta_ingestor_api_proto_init() }
func file_api_v1beta_ingestor_api_proto_init() {
	if File_api_v1beta_ingestor_api_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_v1beta_ingestor_api_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WriteMetricsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1beta_ingestor_api_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MetricsMetadata); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1beta_ingestor_api_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WriteMetricsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_api_v1beta_ingestor_api_proto_msgTypes[1].OneofWrappers = []interface{}{}
	file_api_v1beta_ingestor_api_proto_msgTypes[2].OneofWrappers = []interface{}{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_v1beta_ingestor_api_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_v1beta_ingestor_api_proto_goTypes,
		DependencyIndexes: file_api_v1beta_ingestor_api_proto_depIdxs,
		MessageInfos:      file_api_v1beta_ingestor_api_proto_msgTypes,
	}.Build()
	File_api_v1beta_ingestor_api_proto = out.File
	file_api_v1beta_ingestor_api_proto_rawDesc = nil
	file_api_v1beta_ingestor_api_proto_goTypes = nil
	file_api_v1beta_ingestor_api_proto_depIdxs = nil
}
