// Code generated by mockery. DO NOT EDIT.

package metrics

import (
	context "context"

	grpc "google.golang.org/grpc"

	metrics "github.com/castai/metrics/api/v1beta"

	mock "github.com/stretchr/testify/mock"
)

// MockIngestionAPIClient is an autogenerated mock type for the IngestionAPIClient type
type MockIngestionAPIClient struct {
	mock.Mock
}

type MockIngestionAPIClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIngestionAPIClient) EXPECT() *MockIngestionAPIClient_Expecter {
	return &MockIngestionAPIClient_Expecter{mock: &_m.Mock}
}

// WriteMetrics provides a mock function with given fields: ctx, opts
func (_m *MockIngestionAPIClient) WriteMetrics(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[metrics.WriteMetricsRequest, metrics.WriteMetricsResponse], error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for WriteMetrics")
	}

	var r0 grpc.ClientStreamingClient[metrics.WriteMetricsRequest, metrics.WriteMetricsResponse]
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, ...grpc.CallOption) (grpc.ClientStreamingClient[metrics.WriteMetricsRequest, metrics.WriteMetricsResponse], error)); ok {
		return rf(ctx, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, ...grpc.CallOption) grpc.ClientStreamingClient[metrics.WriteMetricsRequest, metrics.WriteMetricsResponse]); ok {
		r0 = rf(ctx, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(grpc.ClientStreamingClient[metrics.WriteMetricsRequest, metrics.WriteMetricsResponse])
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIngestionAPIClient_WriteMetrics_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WriteMetrics'
type MockIngestionAPIClient_WriteMetrics_Call struct {
	*mock.Call
}

// WriteMetrics is a helper method to define mock.On call
//   - ctx context.Context
//   - opts ...grpc.CallOption
func (_e *MockIngestionAPIClient_Expecter) WriteMetrics(ctx interface{}, opts ...interface{}) *MockIngestionAPIClient_WriteMetrics_Call {
	return &MockIngestionAPIClient_WriteMetrics_Call{Call: _e.mock.On("WriteMetrics",
		append([]interface{}{ctx}, opts...)...)}
}

func (_c *MockIngestionAPIClient_WriteMetrics_Call) Run(run func(ctx context.Context, opts ...grpc.CallOption)) *MockIngestionAPIClient_WriteMetrics_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]grpc.CallOption, len(args)-1)
		for i, a := range args[1:] {
			if a != nil {
				variadicArgs[i] = a.(grpc.CallOption)
			}
		}
		run(args[0].(context.Context), variadicArgs...)
	})
	return _c
}

func (_c *MockIngestionAPIClient_WriteMetrics_Call) Return(_a0 grpc.ClientStreamingClient[metrics.WriteMetricsRequest, metrics.WriteMetricsResponse], _a1 error) *MockIngestionAPIClient_WriteMetrics_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIngestionAPIClient_WriteMetrics_Call) RunAndReturn(run func(context.Context, ...grpc.CallOption) (grpc.ClientStreamingClient[metrics.WriteMetricsRequest, metrics.WriteMetricsResponse], error)) *MockIngestionAPIClient_WriteMetrics_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockIngestionAPIClient creates a new instance of MockIngestionAPIClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIngestionAPIClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIngestionAPIClient {
	mock := &MockIngestionAPIClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
