// Code generated by mockery. DO NOT EDIT.

package grpc

import (
	context "context"

	metadata "google.golang.org/grpc/metadata"

	mock "github.com/stretchr/testify/mock"
)

// MockClientStreamingClient is an autogenerated mock type for the ClientStreamingClient type
type MockClientStreamingClient[Req interface{}, Res interface{}] struct {
	mock.Mock
}

type MockClientStreamingClient_Expecter[Req interface{}, Res interface{}] struct {
	mock *mock.Mock
}

func (_m *MockClientStreamingClient[Req, Res]) EXPECT() *MockClientStreamingClient_Expecter[Req, Res] {
	return &MockClientStreamingClient_Expecter[Req, Res]{mock: &_m.Mock}
}

// CloseAndRecv provides a mock function with no fields
func (_m *MockClientStreamingClient[Req, Res]) CloseAndRecv() (*Res, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for CloseAndRecv")
	}

	var r0 *Res
	var r1 error
	if rf, ok := ret.Get(0).(func() (*Res, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() *Res); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*Res)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockClientStreamingClient_CloseAndRecv_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CloseAndRecv'
type MockClientStreamingClient_CloseAndRecv_Call[Req interface{}, Res interface{}] struct {
	*mock.Call
}

// CloseAndRecv is a helper method to define mock.On call
func (_e *MockClientStreamingClient_Expecter[Req, Res]) CloseAndRecv() *MockClientStreamingClient_CloseAndRecv_Call[Req, Res] {
	return &MockClientStreamingClient_CloseAndRecv_Call[Req, Res]{Call: _e.mock.On("CloseAndRecv")}
}

func (_c *MockClientStreamingClient_CloseAndRecv_Call[Req, Res]) Run(run func()) *MockClientStreamingClient_CloseAndRecv_Call[Req, Res] {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockClientStreamingClient_CloseAndRecv_Call[Req, Res]) Return(_a0 *Res, _a1 error) *MockClientStreamingClient_CloseAndRecv_Call[Req, Res] {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockClientStreamingClient_CloseAndRecv_Call[Req, Res]) RunAndReturn(run func() (*Res, error)) *MockClientStreamingClient_CloseAndRecv_Call[Req, Res] {
	_c.Call.Return(run)
	return _c
}

// CloseSend provides a mock function with no fields
func (_m *MockClientStreamingClient[Req, Res]) CloseSend() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for CloseSend")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockClientStreamingClient_CloseSend_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CloseSend'
type MockClientStreamingClient_CloseSend_Call[Req interface{}, Res interface{}] struct {
	*mock.Call
}

// CloseSend is a helper method to define mock.On call
func (_e *MockClientStreamingClient_Expecter[Req, Res]) CloseSend() *MockClientStreamingClient_CloseSend_Call[Req, Res] {
	return &MockClientStreamingClient_CloseSend_Call[Req, Res]{Call: _e.mock.On("CloseSend")}
}

func (_c *MockClientStreamingClient_CloseSend_Call[Req, Res]) Run(run func()) *MockClientStreamingClient_CloseSend_Call[Req, Res] {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockClientStreamingClient_CloseSend_Call[Req, Res]) Return(_a0 error) *MockClientStreamingClient_CloseSend_Call[Req, Res] {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockClientStreamingClient_CloseSend_Call[Req, Res]) RunAndReturn(run func() error) *MockClientStreamingClient_CloseSend_Call[Req, Res] {
	_c.Call.Return(run)
	return _c
}

// Context provides a mock function with no fields
func (_m *MockClientStreamingClient[Req, Res]) Context() context.Context {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Context")
	}

	var r0 context.Context
	if rf, ok := ret.Get(0).(func() context.Context); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(context.Context)
		}
	}

	return r0
}

// MockClientStreamingClient_Context_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Context'
type MockClientStreamingClient_Context_Call[Req interface{}, Res interface{}] struct {
	*mock.Call
}

// Context is a helper method to define mock.On call
func (_e *MockClientStreamingClient_Expecter[Req, Res]) Context() *MockClientStreamingClient_Context_Call[Req, Res] {
	return &MockClientStreamingClient_Context_Call[Req, Res]{Call: _e.mock.On("Context")}
}

func (_c *MockClientStreamingClient_Context_Call[Req, Res]) Run(run func()) *MockClientStreamingClient_Context_Call[Req, Res] {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockClientStreamingClient_Context_Call[Req, Res]) Return(_a0 context.Context) *MockClientStreamingClient_Context_Call[Req, Res] {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockClientStreamingClient_Context_Call[Req, Res]) RunAndReturn(run func() context.Context) *MockClientStreamingClient_Context_Call[Req, Res] {
	_c.Call.Return(run)
	return _c
}

// Header provides a mock function with no fields
func (_m *MockClientStreamingClient[Req, Res]) Header() (metadata.MD, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Header")
	}

	var r0 metadata.MD
	var r1 error
	if rf, ok := ret.Get(0).(func() (metadata.MD, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() metadata.MD); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(metadata.MD)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockClientStreamingClient_Header_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Header'
type MockClientStreamingClient_Header_Call[Req interface{}, Res interface{}] struct {
	*mock.Call
}

// Header is a helper method to define mock.On call
func (_e *MockClientStreamingClient_Expecter[Req, Res]) Header() *MockClientStreamingClient_Header_Call[Req, Res] {
	return &MockClientStreamingClient_Header_Call[Req, Res]{Call: _e.mock.On("Header")}
}

func (_c *MockClientStreamingClient_Header_Call[Req, Res]) Run(run func()) *MockClientStreamingClient_Header_Call[Req, Res] {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockClientStreamingClient_Header_Call[Req, Res]) Return(_a0 metadata.MD, _a1 error) *MockClientStreamingClient_Header_Call[Req, Res] {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockClientStreamingClient_Header_Call[Req, Res]) RunAndReturn(run func() (metadata.MD, error)) *MockClientStreamingClient_Header_Call[Req, Res] {
	_c.Call.Return(run)
	return _c
}

// RecvMsg provides a mock function with given fields: m
func (_m *MockClientStreamingClient[Req, Res]) RecvMsg(m interface{}) error {
	ret := _m.Called(m)

	if len(ret) == 0 {
		panic("no return value specified for RecvMsg")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(interface{}) error); ok {
		r0 = rf(m)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockClientStreamingClient_RecvMsg_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RecvMsg'
type MockClientStreamingClient_RecvMsg_Call[Req interface{}, Res interface{}] struct {
	*mock.Call
}

// RecvMsg is a helper method to define mock.On call
//   - m interface{}
func (_e *MockClientStreamingClient_Expecter[Req, Res]) RecvMsg(m interface{}) *MockClientStreamingClient_RecvMsg_Call[Req, Res] {
	return &MockClientStreamingClient_RecvMsg_Call[Req, Res]{Call: _e.mock.On("RecvMsg", m)}
}

func (_c *MockClientStreamingClient_RecvMsg_Call[Req, Res]) Run(run func(m interface{})) *MockClientStreamingClient_RecvMsg_Call[Req, Res] {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(interface{}))
	})
	return _c
}

func (_c *MockClientStreamingClient_RecvMsg_Call[Req, Res]) Return(_a0 error) *MockClientStreamingClient_RecvMsg_Call[Req, Res] {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockClientStreamingClient_RecvMsg_Call[Req, Res]) RunAndReturn(run func(interface{}) error) *MockClientStreamingClient_RecvMsg_Call[Req, Res] {
	_c.Call.Return(run)
	return _c
}

// Send provides a mock function with given fields: _a0
func (_m *MockClientStreamingClient[Req, Res]) Send(_a0 *Req) error {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for Send")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*Req) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockClientStreamingClient_Send_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Send'
type MockClientStreamingClient_Send_Call[Req interface{}, Res interface{}] struct {
	*mock.Call
}

// Send is a helper method to define mock.On call
//   - _a0 *Req
func (_e *MockClientStreamingClient_Expecter[Req, Res]) Send(_a0 interface{}) *MockClientStreamingClient_Send_Call[Req, Res] {
	return &MockClientStreamingClient_Send_Call[Req, Res]{Call: _e.mock.On("Send", _a0)}
}

func (_c *MockClientStreamingClient_Send_Call[Req, Res]) Run(run func(_a0 *Req)) *MockClientStreamingClient_Send_Call[Req, Res] {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*Req))
	})
	return _c
}

func (_c *MockClientStreamingClient_Send_Call[Req, Res]) Return(_a0 error) *MockClientStreamingClient_Send_Call[Req, Res] {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockClientStreamingClient_Send_Call[Req, Res]) RunAndReturn(run func(*Req) error) *MockClientStreamingClient_Send_Call[Req, Res] {
	_c.Call.Return(run)
	return _c
}

// SendMsg provides a mock function with given fields: m
func (_m *MockClientStreamingClient[Req, Res]) SendMsg(m interface{}) error {
	ret := _m.Called(m)

	if len(ret) == 0 {
		panic("no return value specified for SendMsg")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(interface{}) error); ok {
		r0 = rf(m)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockClientStreamingClient_SendMsg_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendMsg'
type MockClientStreamingClient_SendMsg_Call[Req interface{}, Res interface{}] struct {
	*mock.Call
}

// SendMsg is a helper method to define mock.On call
//   - m interface{}
func (_e *MockClientStreamingClient_Expecter[Req, Res]) SendMsg(m interface{}) *MockClientStreamingClient_SendMsg_Call[Req, Res] {
	return &MockClientStreamingClient_SendMsg_Call[Req, Res]{Call: _e.mock.On("SendMsg", m)}
}

func (_c *MockClientStreamingClient_SendMsg_Call[Req, Res]) Run(run func(m interface{})) *MockClientStreamingClient_SendMsg_Call[Req, Res] {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(interface{}))
	})
	return _c
}

func (_c *MockClientStreamingClient_SendMsg_Call[Req, Res]) Return(_a0 error) *MockClientStreamingClient_SendMsg_Call[Req, Res] {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockClientStreamingClient_SendMsg_Call[Req, Res]) RunAndReturn(run func(interface{}) error) *MockClientStreamingClient_SendMsg_Call[Req, Res] {
	_c.Call.Return(run)
	return _c
}

// Trailer provides a mock function with no fields
func (_m *MockClientStreamingClient[Req, Res]) Trailer() metadata.MD {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Trailer")
	}

	var r0 metadata.MD
	if rf, ok := ret.Get(0).(func() metadata.MD); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(metadata.MD)
		}
	}

	return r0
}

// MockClientStreamingClient_Trailer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Trailer'
type MockClientStreamingClient_Trailer_Call[Req interface{}, Res interface{}] struct {
	*mock.Call
}

// Trailer is a helper method to define mock.On call
func (_e *MockClientStreamingClient_Expecter[Req, Res]) Trailer() *MockClientStreamingClient_Trailer_Call[Req, Res] {
	return &MockClientStreamingClient_Trailer_Call[Req, Res]{Call: _e.mock.On("Trailer")}
}

func (_c *MockClientStreamingClient_Trailer_Call[Req, Res]) Run(run func()) *MockClientStreamingClient_Trailer_Call[Req, Res] {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockClientStreamingClient_Trailer_Call[Req, Res]) Return(_a0 metadata.MD) *MockClientStreamingClient_Trailer_Call[Req, Res] {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockClientStreamingClient_Trailer_Call[Req, Res]) RunAndReturn(run func() metadata.MD) *MockClientStreamingClient_Trailer_Call[Req, Res] {
	_c.Call.Return(run)
	return _c
}

// NewMockClientStreamingClient creates a new instance of MockClientStreamingClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockClientStreamingClient[Req interface{}, Res interface{}](t interface {
	mock.TestingT
	Cleanup(func())
}) *MockClientStreamingClient[Req, Res] {
	mock := &MockClientStreamingClient[Req, Res]{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
